<x-dashboard.layout title="Signing keys" breadcrumb="Signing keys" :user-name="auth()->user()->name" :user-email="auth()->user()->email" :logout-url="Route::has('logout') ? route('logout') : url('/logout')">
    <div class="space-y-6">
        <header class="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p class="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--dash-primary)]">Cryptographic boundary</p><h1 class="mt-2 text-2xl font-semibold text-[var(--dash-text-heading)]">Signing keys</h1><p class="mt-1 text-sm text-[var(--dash-text-muted)]">Only public metadata is displayed. Private key material is never rendered.</p></div><form method="POST" action="{{ route('admin.keys.rotate') }}" data-confirm="The current signing key will be retired and a new key generated." data-confirm-type="warning" data-confirm-title="Rotate signing key?" data-confirm-btn="Rotate key">@csrf<x-form.button type="submit" size="sm" icon="arrow-repeat">Rotate key</x-form.button></form></header>
        @if($keys->isEmpty())<div class="border border-dashed border-[var(--dash-border)] bg-[var(--dash-card)] px-6 py-14 text-center"><h2 class="font-semibold text-[var(--dash-text-heading)]">No signing keys</h2><p class="mt-1 text-sm text-[var(--dash-text-muted)]">Generate the first signing key through the controlled key boundary.</p></div>@else
            <x-table.wrapper :striped="true"><x-slot:head><x-table.th>Key ID</x-table.th><x-table.th>Algorithm</x-table.th><x-table.th>Status</x-table.th><x-table.th>Activated</x-table.th><x-table.th>Retired</x-table.th><x-table.th>Action</x-table.th></x-slot:head>
                @foreach($keys as $key)<tr><x-table.td><span class="font-mono text-xs">{{ $key->kid }}</span></x-table.td><x-table.td>{{ $key->algorithm }}</x-table.td><x-table.td>{{ $key->status }}</x-table.td><x-table.td>{{ $key->activated_at?->toDateTimeString() ?: '—' }}</x-table.td><x-table.td>{{ $key->retired_at?->toDateTimeString() ?: '—' }}</x-table.td><x-table.td>@if($key->status === 'active')<form method="POST" action="{{ route('admin.keys.revoke', $key) }}" data-confirm="This retires the selected signing key." data-confirm-type="delete" data-confirm-title="Retire signing key?" data-confirm-btn="Retire key">@csrf @method('DELETE')<x-form.button type="submit" size="sm" variant="ghost">Retire</x-form.button></form>@else<span class="text-xs text-[var(--dash-muted)]">Inactive</span>@endif</x-table.td></tr>@endforeach
            </x-table.wrapper><div>{{ $keys->links() }}</div>
        @endif
    </div>
</x-dashboard.layout>
