<x-dashboard.layout title="Signing keys" breadcrumb="Signing keys" :user-name="auth()->user()->name" :user-email="auth()->user()->email" :logout-url="Route::has('logout') ? route('logout') : url('/logout')">
    <div class="space-y-6">
        <x-ui.page-header kicker="Cryptographic boundary" title="Signing keys" description="The public half verifies tokens. The private half stays inside the server and is never rendered or exported.">
            <x-slot:actions><form method="POST" action="{{ route('admin.keys.rotate') }}" data-confirm="The current signing key will be retired and a new key generated." data-confirm-type="warning" data-confirm-title="Rotate signing key?" data-confirm-btn="Rotate key">@csrf<x-form.button type="submit" size="sm" icon="arrow-repeat">Rotate key</x-form.button></form></x-slot:actions>
        </x-ui.page-header>

        <div class="bento-grid">
            <section class="bento-panel bento-panel-hero lg:col-span-7">
                <div class="bento-orbit" aria-hidden="true"></div>
                <div class="relative z-10 flex h-full flex-col justify-between gap-8"><div><span class="bento-kicker">Trust infrastructure</span><h2 class="mt-3 text-3xl font-light tracking-tight text-[var(--dash-text-heading)]">Token signing lifecycle</h2><p class="mt-3 max-w-xl text-sm leading-6 text-[var(--dash-text-muted)]">Every issued token is signed with the active private key. Consumers validate it using the matching public key from JWKS.</p></div><div class="grid gap-3 sm:grid-cols-3"><div class="bento-stat"><span>Keys shown</span><strong>{{ $keys->total() }}</strong></div><div class="bento-stat"><span>Algorithm</span><strong>RS256</strong></div><div class="bento-stat"><span>Endpoint</span><strong>JWKS</strong></div></div></div>
            </section>
            <section class="bento-panel lg:col-span-5"><div class="flex items-start justify-between gap-4"><div><span class="bento-kicker">Operator guide</span><h2 class="bento-title">How rotation works</h2></div><i class="bi bi-shield-check text-xl text-[var(--dash-primary)]" aria-hidden="true"></i></div><ol class="mt-6 space-y-4 text-sm text-[var(--dash-text-muted)]"><li class="flex gap-3"><span class="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[var(--dash-primary-soft)] text-xs font-semibold text-[var(--dash-primary)]">1</span><span>Generate a new key and make it active for new tokens.</span></li><li class="flex gap-3"><span class="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[var(--dash-primary-soft)] text-xs font-semibold text-[var(--dash-primary)]">2</span><span>Publish public keys through the JWKS endpoint.</span></li><li class="flex gap-3"><span class="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[var(--dash-primary-soft)] text-xs font-semibold text-[var(--dash-primary)]">3</span><span>Retain retired keys until existing tokens expire.</span></li></ol></section>

            <section class="bento-panel bento-panel-full !min-h-0 !p-0"><div class="flex flex-col gap-2 border-b border-[var(--dash-border)] px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><span class="bento-kicker">Key registry</span><h2 class="bento-title">Public key metadata</h2></div><span class="text-xs text-[var(--dash-text-muted)]">Private material hidden</span></div>@if($keys->isEmpty())<div class="p-10 text-center text-sm text-[var(--dash-text-muted)]">No signing keys. Generate the first key through the controlled key boundary.</div>@else<div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b border-[var(--dash-border)] text-xs uppercase tracking-wide text-[var(--dash-text-muted)]"><tr><th class="px-6 py-3">Key ID</th><th class="px-6 py-3">Algorithm</th><th class="px-6 py-3">Lifecycle</th><th class="px-6 py-3">Activated</th><th class="px-6 py-3">Action</th></tr></thead><tbody class="divide-y divide-[var(--dash-border)]">@foreach($keys as $key)<tr class="transition-colors hover:bg-[var(--dash-card-hover)]"><td class="px-6 py-4"><span class="font-mono text-xs text-[var(--dash-text-heading)]">{{ $key->kid }}</span><div class="mt-1 text-xs text-[var(--dash-text-muted)]">Published through JWKS</div></td><td class="px-6 py-4 font-mono text-xs">{{ $key->algorithm }}</td><td class="px-6 py-4"><x-status-badge :value="$key->status" /></td><td class="px-6 py-4 text-xs text-[var(--dash-text-muted)]">{{ $key->activated_at?->format('d M Y, H:i') ?: '—' }}</td><td class="px-6 py-4">@if($key->status === 'active')<form method="POST" action="{{ route('admin.keys.revoke', $key) }}" data-confirm="This retires the selected signing key." data-confirm-type="delete" data-confirm-title="Retire signing key?" data-confirm-btn="Retire key">@csrf @method('DELETE')<x-form.button type="submit" size="sm" variant="ghost">Retire</x-form.button></form>@else<span class="text-xs text-[var(--dash-muted)]">Retired {{ $key->retired_at?->format('d M Y') ?: '—' }}</span>@endif</td></tr>@endforeach</tbody></table></div><div class="border-t border-[var(--dash-border)] p-4">{{ $keys->links() }}</div>@endif</section>
        </div>
    </div>
</x-dashboard.layout>